const defaultRecipes=[
{id:1,name:"Pasta met kip",ingredients:"pasta kip paprika ui",category:"Avondeten",time:30,price:9.50,image:"https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=900",owner:"demo"},
{id:2,name:"Vegetarische bowl",ingredients:"rijst avocado groenten",category:"Vegetarisch",time:20,price:7.25,image:"https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=900",owner:"demo"},
{id:3,name:"Pittige curry",ingredients:"rijst curry groenten kruiden",category:"Pittig",time:25,price:8,image:"https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=900",owner:"demo"}];
function getRecipes(){let data=localStorage.getItem("recipes");if(!data){localStorage.setItem("recipes",JSON.stringify(defaultRecipes));return defaultRecipes}return JSON.parse(data)}
function saveRecipes(data){localStorage.setItem("recipes",JSON.stringify(data))}
function getUsers(){let users=JSON.parse(localStorage.getItem("users")||"[]");users=users.filter(u=>u.username!=="admin"&&u.username!=="admin103425");users.push({username:"admin103425",password:"Rotterdammers",role:"admin"});localStorage.setItem("users",JSON.stringify(users));return users}
function currentUser(){return JSON.parse(sessionStorage.getItem("currentUser")||"null")}
function updateNavigation(){const user=currentUser(),admin=document.getElementById("adminNav"),login=document.getElementById("loginNav"),logout=document.getElementById("logoutNav"),profile=document.getElementById("profileNav");if(admin)admin.classList.toggle("hidden",!user||user.role!=="admin");if(login)login.classList.toggle("hidden",!!user);if(logout)logout.classList.toggle("hidden",!user);if(profile)profile.classList.toggle("hidden",!user)}
function logout(){sessionStorage.removeItem("currentUser");location.href="index.html"}
function recipeCard(r){return '<article class="food-card"><img src="'+r.image+'" alt="'+r.name+'"><div><small>'+r.category.toUpperCase()+' · '+r.time+' MIN · € '+Number(r.price).toFixed(2)+'</small><h3>'+r.name+'</h3><p>'+r.ingredients+'</p><a href="recept-detail.html">Bekijk recept</a></div></article>'}
function filterRecipes(){const grid=document.getElementById("recipeGrid");if(!grid)return;let r=getRecipes(),q=(document.getElementById("search")?.value||"").toLowerCase(),c=document.getElementById("category")?.value||"",s=document.getElementById("sort")?.value||"";r=r.filter(x=>(x.name+" "+x.ingredients).toLowerCase().includes(q)&&(!c||x.category===c));if(s==="price")r.sort((a,b)=>a.price-b.price);if(s==="time")r.sort((a,b)=>a.time-b.time);grid.innerHTML=r.map(recipeCard).join("")}
function requireUser(){if(document.getElementById("recipeForm")&&!currentUser())location.href="login.html"}
function requireAdmin(){if(document.getElementById("adminPage")&&(!currentUser()||currentUser().role!=="admin"))location.href="admin-login.html"}
function deleteRecipe(id){saveRecipes(getRecipes().filter(r=>r.id!==id));renderMine();renderAdmin();filterRecipes()}
function renderMine(){const el=document.getElementById("myRecipes");if(!el)return;const user=currentUser();if(!user)return;const list=getRecipes().filter(r=>r.owner===user.username||user.role==="admin");el.innerHTML=list.map(r=>'<article class="manage-card"><img src="'+r.image+'" alt="'+r.name+'"><div><strong>'+r.name+'</strong><span>'+r.category+' · '+r.time+' min · € '+Number(r.price).toFixed(2)+'</span></div><div class="manage-actions"><button onclick="editRecipe('+r.id+')">Aanpassen</button><button class="delete-button" onclick="deleteRecipe('+r.id+')">Verwijderen</button></div></article>').join("")||"<p>Je hebt nog geen recepten geplaatst.</p>"}
function editRecipe(id){const r=getRecipes().find(x=>x.id===id);if(!r)return;editId.value=r.id;name.value=r.name;ingredients.value=r.ingredients;formCategory.value=r.category;time.value=r.time;price.value=r.price;image.value=r.image;scrollTo(0,0)}
function renderAdmin(){const el=document.getElementById("adminRecipes");if(!el)return;el.innerHTML=getRecipes().map(r=>'<article class="admin-card"><img src="'+r.image+'" alt="'+r.name+'"><div><strong>'+r.name+'</strong><span>'+r.category+' · '+r.time+' min · € '+Number(r.price).toFixed(2)+'</span></div><button class="delete-button" onclick="deleteRecipe('+r.id+')">Verwijderen</button></article>').join("")}
document.getElementById("registerForm")?.addEventListener("submit",e=>{e.preventDefault();const u=registerUsername.value.trim(),p=registerPassword.value,p2=registerPassword2.value,msg=document.getElementById("registerMessage"),users=getUsers();if(p!==p2){msg.textContent="De wachtwoorden zijn niet hetzelfde.";return}if(users.some(x=>x.username.toLowerCase()===u.toLowerCase())){msg.textContent="Deze gebruikersnaam bestaat al.";return}users.push({username:u,password:p,role:"user"});localStorage.setItem("users",JSON.stringify(users));sessionStorage.setItem("currentUser",JSON.stringify({username:u,role:"user"}));location.href="profiel.html"});
document.getElementById("loginForm")?.addEventListener("submit",e=>{e.preventDefault();const user=getUsers().find(x=>x.username===loginUsername.value.trim()&&x.password===loginPassword.value);if(!user){loginMessage.textContent="Gebruikersnaam of wachtwoord klopt niet.";return}sessionStorage.setItem("currentUser",JSON.stringify({username:user.username,role:user.role}));location.href=user.role==="admin"?"admin.html":"profiel.html"});
document.getElementById("adminLoginForm")?.addEventListener("submit",e=>{e.preventDefault();const user=getUsers().find(x=>x.username===adminUsername.value.trim()&&x.password===adminPassword.value&&x.role==="admin");if(!user){adminLoginMessage.textContent="Dit is geen geldig admin account.";return}sessionStorage.setItem("currentUser",JSON.stringify({username:user.username,role:user.role}));location.href="admin.html"});
document.getElementById("recipeForm")?.addEventListener("submit",e=>{e.preventDefault();const user=currentUser();if(!user)return;let list=getRecipes(),id=Number(editId.value);const data={id:id||Date.now(),name:name.value,ingredients:ingredients.value,category:formCategory.value,time:Number(time.value),price:Number(price.value),image:image.value||defaultRecipes[0].image,owner:user.username};if(id)list=list.map(x=>x.id===id?data:x);else list.push(data);saveRecipes(list);e.target.reset();editId.value="";renderMine()});
document.getElementById("adminRecipeForm")?.addEventListener("submit",e=>{e.preventDefault();const user=currentUser();if(!user||user.role!=="admin")return;const list=getRecipes();list.push({id:Date.now(),name:adminRecipeName.value,ingredients:adminIngredients.value,category:adminCategory.value,time:Number(adminTime.value),price:Number(adminPrice.value),image:adminImage.value||defaultRecipes[0].image,owner:"admin"});saveRecipes(list);e.target.reset();renderAdmin()});
document.getElementById("search")?.addEventListener("input",filterRecipes);document.getElementById("category")?.addEventListener("change",filterRecipes);document.getElementById("sort")?.addEventListener("change",filterRecipes);
getUsers();updateNavigation();requireUser();requireAdmin();filterRecipes();renderMine();renderAdmin();