const defaults=[{id:1,name:"Pasta met kip",ingredients:"pasta kip paprika ui",category:"Avondeten",time:30,price:9.5,image:"https://images.pexels.com/photos/4147875/pexels-photo-4147875.jpeg?auto=compress&cs=tinysrgb&w=800",owner:"demo"},{id:2,name:"Vegetarische bowl",ingredients:"groenten rijst avocado",category:"Vegetarisch",time:20,price:7.25,image:"https://images.pexels.com/photos/4638384/pexels-photo-4638384.jpeg?auto=compress&cs=tinysrgb&w=800",owner:"demo"},{id:3,name:"Pittige pan",ingredients:"tomaat kruiden groenten",category:"Pittig",time:25,price:8,image:"https://images.pexels.com/photos/6126973/pexels-photo-6126973.jpeg?auto=compress&cs=tinysrgb&w=800",owner:"demo"}];
function getRecipes(){const saved=localStorage.getItem("recipes");if(!saved){localStorage.setItem("recipes",JSON.stringify(defaults));return defaults}return JSON.parse(saved)}
function saveRecipes(r){localStorage.setItem("recipes",JSON.stringify(r))}
function card(r){return '<article class="food-card"><img src="'+r.image+'" alt="'+r.name+'"><div><small>'+r.category.toUpperCase()+' · '+r.time+' MIN · € '+Number(r.price).toFixed(2)+'</small><h3>'+r.name+'</h3><p>'+r.ingredients+'</p><a href="recept-detail.html">Bekijk recept</a></div></article>'}
function filterRecipes(){let r=getRecipes();const q=(document.getElementById("search")?.value||"").toLowerCase();const c=document.getElementById("category")?.value||"";const s=document.getElementById("sort")?.value||"";r=r.filter(x=>(x.name+" "+x.ingredients).toLowerCase().includes(q)&&(!c||x.category===c));if(s==="price")r.sort((a,b)=>a.price-b.price);if(s==="time")r.sort((a,b)=>a.time-b.time);const g=document.getElementById("recipeGrid");if(g)g.innerHTML=r.map(card).join("")}
function renderMine(){const el=document.getElementById("myRecipes");if(!el)return;el.innerHTML=getRecipes().map(r=>'<article class="manage-card"><img src="'+r.image+'" alt="'+r.name+'"><div><strong>'+r.name+'</strong><span>'+r.category+' · '+r.time+' min · € '+Number(r.price).toFixed(2)+'</span></div><div class="manage-actions"><button onclick="editRecipe('+r.id+')">Aanpassen</button><button class="delete-button" onclick="deleteRecipe('+r.id+')">Verwijderen</button></div></article>').join("")}
function editRecipe(id){const r=getRecipes().find(x=>x.id===id);if(!r)return;editId.value=r.id;name.value=r.name;ingredients.value=r.ingredients;formCategory.value=r.category;time.value=r.time;price.value=r.price;image.value=r.image;window.scrollTo(0,0)}
function deleteRecipe(id){saveRecipes(getRecipes().filter(r=>r.id!==id));renderMine();renderAdmin();filterRecipes()}
function renderAdmin(){const el=document.getElementById("adminRecipes");if(!el)return;el.innerHTML=getRecipes().map(r=>'<article class="admin-card"><img src="'+r.image+'" alt="'+r.name+'"><div><strong>'+r.name+'</strong><span>'+r.category+' · '+r.time+' min · € '+Number(r.price).toFixed(2)+'</span></div><button class="delete-button" onclick="deleteRecipe('+r.id+')">Verwijderen</button></article>').join("")}
document.getElementById("recipeForm")?.addEventListener("submit",e=>{e.preventDefault();let r=getRecipes();const id=Number(editId.value);const data={id:id||Date.now(),name:name.value,ingredients:ingredients.value,category:formCategory.value,time:Number(time.value),price:Number(price.value),image:image.value||defaults[0].image,owner:"user"};if(id)r=r.map(x=>x.id===id?data:x);else r.push(data);saveRecipes(r);e.target.reset();editId.value="";renderMine()});
document.getElementById("search")?.addEventListener("input",filterRecipes);document.getElementById("category")?.addEventListener("change",filterRecipes);document.getElementById("sort")?.addEventListener("change",filterRecipes);filterRecipes();renderMine();renderAdmin();